"""add source event id

Revision ID: 66a1e2313f18
Revises: 8a2f9726d2b9
Create Date: 2026-02-18 16:56:17.966309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a1e2313f18'
down_revision: Union[str, Sequence[str], None] = '8a2f9726d2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_service_events', sa.Column('source_event_id', sa.Text(), nullable=True))
    op.add_column('raw_service_events', sa.Column('sourced', sa.Text(), nullable=False))
    op.create_index(op.f('ix_raw_service_events_source_event_id'), 'raw_service_events', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_raw_service_events_sourced'), 'raw_service_events', ['sourced'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_service_events_sourced'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_source_event_id'), table_name='raw_service_events')
    op.drop_column('raw_service_events', 'sourced')
    op.drop_column('raw_service_events', 'source_event_id')
    # ### end Alembic commands ###
