"""created slot metrics daytype

Revision ID: 764331a586c4
Revises: 957deee2742c
Create Date: 2026-02-22 11:14:58.126949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764331a586c4'
down_revision: Union[str, Sequence[str], None] = '957deee2742c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_metrics_daytype',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('day_type', sa.Text(), nullable=False),
    sa.Column('dep_hhmm', sa.Text(), nullable=False),
    sa.Column('disruption_prob', sa.Float(), nullable=False),
    sa.Column('cancellation_prob', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('effective_sample_size', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('metric_date', 'model_version', 'operator', 'origin', 'destination', 'day_type', 'dep_hhmm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_metrics_daytype')
    # ### end Alembic commands ###
