"""init schema

Revision ID: 8a2f9726d2b9
Revises: 
Create Date: 2026-02-18 16:31:24.680577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a2f9726d2b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commute_intents',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_service_key', sa.Text(), nullable=True),
    sa.Column('alt_service_key', sa.Text(), nullable=True),
    sa.Column('recommendation_shown', sa.Boolean(), nullable=False),
    sa.Column('risk_delta', sa.Float(), nullable=True),
    sa.Column('final_service_key', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('outcome_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_index(op.f('ix_commute_intents_user_id'), 'commute_intents', ['user_id'], unique=False)
    op.create_table('daily_slot_agg',
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('dep_hhmm', sa.Text(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('n_services', sa.Integer(), nullable=False),
    sa.Column('n_cancelled', sa.Integer(), nullable=False),
    sa.Column('n_delayed_gt5', sa.Integer(), nullable=False),
    sa.Column('n_disrupted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('service_date', 'operator', 'origin', 'destination', 'dep_hhmm')
    )
    op.create_index(op.f('ix_daily_slot_agg_day_of_week'), 'daily_slot_agg', ['day_of_week'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_event_name'), 'event_log', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_log_session_id'), 'event_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_log_user_id'), 'event_log', ['user_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_table('raw_service_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('scheduled_departure_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('arrival_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('service_key', sa.Text(), nullable=False),
    sa.Column('source_run_id', sa.UUID(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_service_events_destination'), 'raw_service_events', ['destination'], unique=False)
    op.create_index(op.f('ix_raw_service_events_operator'), 'raw_service_events', ['operator'], unique=False)
    op.create_index(op.f('ix_raw_service_events_origin'), 'raw_service_events', ['origin'], unique=False)
    op.create_index(op.f('ix_raw_service_events_scheduled_departure_ts'), 'raw_service_events', ['scheduled_departure_ts'], unique=False)
    op.create_index(op.f('ix_raw_service_events_service_date'), 'raw_service_events', ['service_date'], unique=False)
    op.create_index(op.f('ix_raw_service_events_service_key'), 'raw_service_events', ['service_key'], unique=False)
    op.create_index(op.f('ix_raw_service_events_source_run_id'), 'raw_service_events', ['source_run_id'], unique=False)
    op.create_table('slot_metrics',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('dep_hhmm', sa.Text(), nullable=False),
    sa.Column('disruption_prob', sa.Float(), nullable=False),
    sa.Column('cancellation_prob', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('effective_sample_size', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('metric_date', 'model_version', 'operator', 'origin', 'destination', 'day_of_week', 'dep_hhmm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_metrics')
    op.drop_index(op.f('ix_raw_service_events_source_run_id'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_service_key'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_service_date'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_scheduled_departure_ts'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_origin'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_operator'), table_name='raw_service_events')
    op.drop_index(op.f('ix_raw_service_events_destination'), table_name='raw_service_events')
    op.drop_table('raw_service_events')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_event_log_user_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_session_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_name'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_daily_slot_agg_day_of_week'), table_name='daily_slot_agg')
    op.drop_table('daily_slot_agg')
    op.drop_index(op.f('ix_commute_intents_user_id'), table_name='commute_intents')
    op.drop_table('commute_intents')
    # ### end Alembic commands ###
