"""changed conflict

Revision ID: 957deee2742c
Revises: 523c9c733929
Create Date: 2026-02-20 13:01:48.839475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957deee2742c'
down_revision: Union[str, Sequence[str], None] = '523c9c733929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_service_events_service_key'), table_name='raw_service_events')
    op.create_index(op.f('ix_raw_service_events_service_key'), 'raw_service_events', ['service_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_service_events_service_key'), table_name='raw_service_events')
    op.create_index(op.f('ix_raw_service_events_service_key'), 'raw_service_events', ['service_key'], unique=False)
    # ### end Alembic commands ###
